
language: php

php: 7.0

git:
  depth: 5

before_install:
  - nvm install v8.1
  - npm -v

install:
  - composer install
  - npm install

before_script:
  - composer copy-dotenv
  - composer copy-conf
  - composer mkdir
  #- composer chown  # chown: invalid user: ‘nginx:nginx’
  - composer symlink-data
  - npm run symlink-js
  - npm run build
  - npm run min
  - npm run hash-js

script: composer test

after_script:
  - composer version.json
  - composer validate
  - ls -alh
  - ls -alh public_html/assets/
  - git status

# End.
