
language: php

php: 7.0

git:
  depth: 5

before_install: nvm install v8.1

install:
  - composer prepare
  - composer install
  - composer npm-install

before_script: composer build
  #- composer chown  # chown: invalid user: ‘nginx:nginx’

script: composer test

after_script:
  - composer validate
  - ls -alh
  - ls -alh public_html/assets/
  #- git status

# End.
