
language: php

php: 7.0

git:
  depth: 8

install: composer install

before_script:
  - composer copy-conf
  - composer mkdir
  #- composer chown  # chown: invalid user: ‘nginx:nginx’
  - composer patch

script: composer test

after_script:
  - composer validate
  - ls -alh

# End.
