
language: php

php: 7.0

git:
  depth: 8

before_install:
  - nvm install v8.1
  - npm -v

install:
  - composer install
  - npm install

before_script:
  - composer copy-conf
  - composer mkdir
  #- composer chown  # chown: invalid user: ‘nginx:nginx’
  - npm run link

script: composer test

after_script:
  - composer validate
  - ls -alh

# End.
